src/main/java/org/tikv/PDClient.java
src/main/java/org/tikv/ReadOnlyPDClient.java
src/main/java/org/tikv/region/RegionManager.java
src/main/java/org/tikv/region/TiRegion.java
src/test/java/org/tikv/RawKVClientTest.java

When using raw APIs, regions should not be decoded as it was when using Txn APIs.
@huachaohuang PTAL.

Fix error in region decode when using rawKVClient APIs

---

.gitignore
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/tikv/common/operation/KVErrorHandler.java
src/test/java/org/tikv/common/KVMockServer.java

Current gradle build fails because kvproto changed the package name `StaleEpoch` to `EpochNotMatch`. This PR updates gradle build and applies its new name in kvproto. It also separates `build.gradle` changes from #48

Fix gradle build

---

src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
src/main/java/org/tikv/common/operation/iterator/ScanIterator.java

When ScanIterator gets an Error from TiKV indicating region info needs to be refreshed, e.g., region epoch is not match, we should retry with a new client to prevent unrecoverable failure.

Fix ScanIterator may fail when an error encounters

---

src/main/java/org/tikv/common/columnar/TiBlockColumnVector.java
src/main/java/org/tikv/common/columnar/TiChunkColumnVector.java
src/main/java/org/tikv/common/types/AbstractDateTimeType.java
src/main/java/org/tikv/common/types/DateType.java

When timezone is set to positive, the date type value may be incorrectly set with `+1` day

Fix incorrect date type value when timezone is set

---

src/main/java/org/tikv/common/codec/Codec.java

When enum inserted is empty string `''`, its index value is actually 0.
https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-indexes

Fix enum index out of range error

---

src/main/java/org/tikv/common/codec/Codec.java

#106  should be bounded -1 rather than 0, because the value of idx was substracted before.

Fix empty enum type

---

pom.xml
src/main/java/org/tikv/common/columnar/TiChunkColumnVector.java
src/main/java/org/tikv/common/region/RegionStoreClient.java

The `maven-assembly` plugin falsely re-introduces shaded dependencies.
It is now removed in this PR.

Fix falsely shaded dependencies

---

src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
src/main/java/org/tikv/raw/RawKVClient.java

Current APIs for `rawScan` limits the maximum keys to be scanned.
Add a new API to remove this limit. 

Add raw scan api without limit

---

README.md
src/main/java/org/tikv/common/TiSession.java
src/test/java/org/tikv/raw/RawKVClientTest.java

As shown in examples, users should use `TiSession.getInstance` rather than `TiSession.create` to initialize a `TiSession`. 

Modify TiSession API document

---

src/main/java/org/tikv/common/KVClient.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/util/Batch.java
src/main/java/org/tikv/common/util/ClientUtils.java
src/main/java/org/tikv/common/util/DeleteRange.java
src/main/java/org/tikv/raw/RawKVClient.java
src/main/java/org/tikv/txn/KVClient.java

When all TiKVs are down, the batch process may hang. And can not recover before the TiKV is up. The backoff did not work properly in this situation.
Fixes this behavior by throwing an exception when the requests wait till backoff time.

Fix batch retry hanging when tikv is down

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/HostMapping.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/ReadOnlyPDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/pd/PDUtils.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/util/ChannelFactory.java
src/main/java/org/tikv/common/util/RangeSplitter.java

Add network mapping for Java Client.
By using `-Dtikv.network.mapping=<config-name>`, we can make the client use the corresponding host mapping strategy stored in PD's ETCD in advance.
The format of KV is as follows:
```
key: /client/url-mapping/<conf-name>/<Inet-ip>
value: <mapped-ip>
```

Add Network Mapping

---

pom.xml
src/main/java/org/tikv/common/columnar/TiBlockColumnVector.java
src/main/java/org/tikv/common/columnar/datatypes/AutoGrowByteBuffer.java
src/main/java/org/tikv/common/columnar/datatypes/CHType.java
src/main/java/org/tikv/common/columnar/datatypes/CHTypeString.java
src/main/java/org/tikv/common/util/MemoryUtil.java

Hi,
This is my 1st attempt at fixing https://github.com/tikv/client-java/issues/154 .
The problem when building/running with JDK9+ is not `sun.misc.Unsafe`. It is still there up to JDK15, you just have to `--add-module=jdk.unsupported`. In JDK16 it is encapsulated (you have to also add `--add-exports=...`) while in JDK17 it might get removed. The problem are: `sun.misc.Cleaner` which was removed in JDK9 (moved to `jdk.internal.ref` package) and `sun.nio.ch.DirectBuffer` interface which got encapsulated in JDK9.
So instead of building alternative versions of classes such as `MemoryUtil` compiled with and for JDK9+ and packaged into a multi-release JAR, I opted for simpler approach. I got rid of DirectByteBuffer usage (mostly they were used in TiBlockColumnVector) and replaced them with …

Allow building on JDK9+ by getting rid of DirectByteBuffer dependency

---

src/main/java/org/tikv/common/operation/iterator/DAGIterator.java

https://github.com/pingcap/tispark/pull/2010
oom during calling `client.coprocess` will cause missing data bug!
should not set `eof = true` if oom occures during calling `client.coprocess`
Tests 
- Unit test
- No code
Code changes
Side effects

fix oom cause missing data bug

---

src/main/java/org/tikv/common/PDClient.java

When my main thread is finished with all the tasks processed, this pool will prevent my program shutting down.
[TiDBCatalogDemo.java](https://github.com/tidb-incubator/TiBigData/blob/master/flink/flink-1.12/src/main/java/io/tidb/bigdata/flink/tidb/examples/TiDBCatalogDemo.java)
1. Create a daemon thread pool for etcd client
2. Add name format for ExecutorService
Test in local with version 3.0.1, thread stack : 
```
"PDClient-tiflash-replica-pool-0@8667" daemon prio=5 tid=0x46 nid=NA waiting
java.lang.Thread.State: WAITING
at sun.misc.Unsafe.park(Unsafe.java:-1)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchron …
```

Create a daemon thread pool for etcd client & Add name format for ExecutorService

---

src/main/java/org/tikv/common/region/RegionManager.java

When store id does not exist in PD, we should invalidate all RegionCache on this store
Tests 

invalidate all region cache on store when store id not found

---

src/main/java/org/tikv/common/exception/RegionException.java
src/main/java/org/tikv/common/operation/KVErrorHandler.java
src/main/java/org/tikv/common/util/Batch.java

backoff may be called concurrently.
force clone before backoffer is passed to batch requests
Tests 

Fix potential concurrent call when backoff

---

.ci/integration_test.groovy

fix a jenkins error on new ci: Caused: java.io.NotSerializableException: java.util.regex.Matcher
fix a jenkins error on new ci: Caused: java.io.NotSerializableException: java.util.regex.Matcher
- regex variable need set to null
Tests 
- Unit test

fix error on new ci

---

pom.xml
src/main/java/org/tikv/cdc/CDCClient.java
src/main/java/org/tikv/cdc/CDCConfig.java
src/main/java/org/tikv/cdc/CDCEvent.java
src/main/java/org/tikv/cdc/RegionCDCClient.java
src/main/java/org/tikv/common/codec/TableCodec.java
src/main/java/org/tikv/common/codec/TableCodecV1.java
src/main/java/org/tikv/common/codec/TableCodecV2.java
src/main/java/org/tikv/txn/TwoPhaseCommitter.java

This PR adds the pure java implementation of CDCClient which comunicates directly with TiKV with GRPC for change logs. It also includes some tiny changes to make TiFlink's implementation easier.
For details about TiFlink, please see [this link](https://internals.tidb.io/t/topic/124).

Add CDCClient to client-java with a few tiny changes for TiFlink

---

scripts/proto.sh
shell.nix

* add shell.nix for Nixer
* refine `srcipts/proto.sh`
Tests 

improve build scripts

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/PDErrorHandler.java
src/test/java/org/tikv/common/PDMockServer.java

close https://github.com/tikv/client-java/issues/179
When PD request is retried when leader is down, the leader info is not updated, so it will fail for at least 60s until the leader info is correct.

Fix pd retry not recovered for 60s

---

src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/raw/RawKVClientTest.java

This pull request adds `batchScanKeys` for `RawClient` just like [the API](https://www.tikv.dev/doc/rust-client/tikv_client/raw/client/struct.Client.html#method.batch_scan_keys) provided in Rust client: 
Tests 
- Unit test
Code changes
Side effects

rawclient: add batch scan keys

---

src/main/java/org/tikv/common/operation/KVErrorHandler.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/RegionStoreClient.java

Tests 
- Unit test
- No code
Code changes
Side effects

refactor kverrorhandler

---

src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/raw/RawKVClientTest.java

Close #187 
Change the check condition for the scan operations to allow empty start key.
Tests 
- Unit test

Fix scan exception when the start key is empty

---

pom.xml
src/main/java/org/tikv/common/DefaultHostMapping.java
src/main/java/org/tikv/common/HostMapping.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/ReadOnlyPDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/region/TiRegion.java
src/main/java/org/tikv/common/replica/FollowerReplicaSelector.java
src/main/java/org/tikv/common/replica/LeaderFollowerReplicaSelector.java
src/main/java/org/tikv/common/replica/LeaderReplicaSelector.java
src/main/java/org/tikv/common/replica/Region.java
src/main/java/org/tikv/common/replica/ReplicaSelector.java
src/main/java/org/tikv/common/replica/Store.java
src/test/java/org/tikv/common/MockServerTest.java
src/test/java/org/tikv/common/PDClientTest.java
src/test/java/org/tikv/common/RegionManagerTest.java
src/test/java/org/tikv/common/RegionStoreClientTest.java
src/test/java/org/tikv/txn/ReplicaReadTest.java

Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Pass in more meta data so ReplicaSelector can make better decision at runtime
Pass in more meta data so ReplicaSelector can make better decision at runtime
Tests 
- Unit test
Code changes
Side effects

Support select replica with rich meta data

---

README.md
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/raw/CASTest.java
src/test/java/org/tikv/raw/RawKVClientTest.java

close https://github.com/tikv/client-java/issues/212
Currently, users should pass the parameter `atomic`  to funcions like`put`、`batchPut`、`delete`、`batchDelete` when using `CAS` in `RawKVClient`.
Add a config `tikv.enable_atomic_for_cas` replacing the `atomic` parameter on each write function like `put`、`delete`.
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to be included in the …

Refactor RawKVClient CAS API

---

README.md
metrics/grafana/client_java_summary.json
src/main/java/org/tikv/common/MetricsServer.java
src/main/java/org/tikv/common/TiSession.java
src/test/java/org/tikv/raw/MetricsTest.java

close https://github.com/tikv/client-java/issues/218
Currently, only one `TiSession` is supported with metrics exporting.
- Support metrics with multiple `TiSessions` with the same port
- Do not support multiple `TiSessions` with different ports
Tests 
- Unit test
- No code
Code changes
Side effects

Support metrics with multiple TiSessions with the same port

---

README.md
metrics/grafana/client_java_summary.json
src/main/java/org/tikv/common/MetricsServer.java
src/main/java/org/tikv/common/TiSession.java
src/test/java/org/tikv/raw/MetricsTest.java

cherry-pick #220 to release-3.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
git pr https://github.com/tikv/client-java/pull/221
```
After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/client-java.git pr/221:release-3.1-630e1513e9cf
```
---
close https://github.com/tikv/client-java/issues/218
Currently, only one `TiSession` is supported with metrics exporting.
- Support metrics with multiple `TiSessions` with the same port
- Do not support multiple `TiSessions` with different ports
Tests 
- Unit test
- No code
Code changes
- Has …

Support metrics with multiple TiSessions with the same port (#220)

---

src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/region/TiRegion.java
src/main/java/org/tikv/common/region/TiStore.java
src/main/java/org/tikv/common/region/UnreachableStoreChecker.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/common/MockServerTest.java

Tests 
- Unit test
- No code
Code changes
Side effects

Forward request by store

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Tests 
- Unit test
- No code
Code changes
Side effects

Refactor Region Cache to reduce lock

---

src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/MetricsServer.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/KVErrorHandler.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionCache.java
src/main/java/org/tikv/common/region/RegionErrorReceiver.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/region/StoreHealthyChecker.java
src/main/java/org/tikv/common/region/TiRegion.java
src/main/java/org/tikv/common/region/TiStore.java
src/main/java/org/tikv/common/region/UnreachableStoreChecker.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Tests 
- Unit test
- No code
Code changes
Side effects

Try other peer when current leader of this region is not available.

---

.ci/integration_test.groovy
README.md
scripts/proto.sh
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/importer/ImporterClient.java
src/main/java/org/tikv/common/importer/ImporterStoreClient.java
src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java
src/main/java/org/tikv/common/region/RegionCache.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/region/TiRegion.java
src/main/java/org/tikv/common/util/BackOffer.java
src/main/java/org/tikv/common/util/ClientUtils.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/common/importer/RawKVIngestTest.java
src/test/java/org/tikv/common/importer/RegionSplitTest.java
src/test/java/org/tikv/common/importer/SwitchTiKVModeTest.java
src/test/java/org/tikv/util/TestUtils.java

This is a subtask of https://github.com/tikv/tikv/issues/10563.
TiKV java client support Bulk Load using the [ingest API](https://github.com/pingcap/kvproto/blob/release-5.0/proto/import_sstpb.proto#L53).
- support RawKV  Region Split
- support switch TiKV to import mode
- support rawWrite API to ingest data
this PR depends on:
- https://github.com/tikv/tikv/pull/10524/
- https://github.com/pingcap/kvproto/pull/779
Tests 
- Unit test
- No code
Code changes
Side effects
- Need …

RawKV support SST Ingest using KVStream interface

---

src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Tests 
- Unit test
- No code
Code changes
Side effects

fix backoff time

---

src/main/java/org/tikv/common/TiSession.java
src/test/java/org/tikv/common/TiSessionTest.java

TiSession support graceful close
Current `TiSession.close` call `ExecutorService.shutdownNow` directly.
Add a new function `TiSession.closeAwaitTermination`:
1. call `ExecutorService.shutdown` 
2. check status using `ExecutorService.isTerminated`, if all terminated return
3. if timeout, call `ExecutorService.shutdown` 
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to be included in …

TiSession support graceful close

---

src/main/java/org/tikv/common/TiSession.java

refactor TiSession.getSwitchTiKVModeClient
use Singleton pattern
Tests 
- Unit test
- No code
Code changes
Side effects

refactor TiSession.getSwitchTiKVModeClient

---

src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Reverts tikv/client-java#241 because test fails
https://ci.pingcap.net/blue/organizations/jenkins/tikv-client-java_ghpr_integration_test/detail/tikv-client-java_ghpr_integration_test/130/pipeline/
```
[2021-08-05T02:42:58.333Z] testRetryPolicy(org.tikv.common.PDClientTest)  Time elapsed: 0.638 sec  <<< FAILURE!
[2021-08-05T02:42:58.333Z] java.lang.AssertionError
[2021-08-05T02:42:58.333Z] 	at org.junit.Assert.fail(Assert.java:86)
[2021-08-05T02:42:58.333Z] 	at org.junit.Assert.fail(Assert.java:95)
[2021-08-05T02:42:58.333Z] 	at org.tikv.common.PDClientTest.testRetryPolicy(PDClientTest.java:203)
[2021-08-05T02:42:58.333Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-08-05T02:42:58.333Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62 …
```

Revert "fix backoff time"

---

README.md
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/raw/RawKVClient.java

cherry pick https://github.com/tikv/client-java/pull/246/

add configration parameter for RawKV timeout (#246)

---

src/main/java/org/tikv/common/region/TiStore.java

When I use it in Tispark, the following exception will be thrown
```
Caused by: java.io.NotSerializableException: org.tikv.common.region.TiStore
Serialization stack:
- object not serializable (class: org.tikv.common.region.TiStore, value: org.tikv.common.region.TiStore@1f547af8)
- writeObject data (class: java.util.ArrayList)
- object (class java.util.ArrayList, [org.tikv.common.region.TiStore@1f547af8, org.tikv.common.region.TiStore@701c482e, org.tikv.common.region.TiStore@4738131e])
- field (class: org.tikv.common.region.TiRegion, name: stores, type: interface java.util.List)
- object (class org.tikv.common.region.TiRegion, {Region[2009] ConfVer[5] Version[8] Store[4] KeyRange[]:[bNmuyJQt]})
- writeObject data (class: scala.collection.immutable.List$SerializationProxy)
- object (class …
```

TiStore: add implement Serializable

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/importer/ImporterStoreClient.java

```
1298 [grpc-default-executor-2] ERROR org.tikv.common.importer.ImporterStoreClient  - Error during raw write!
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9905125ns. [remote_addr=/172.16.4.76:22365]
at io.grpc.Status.asRuntimeException(Status.java:533)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at …
```

add parameter: ingest grpc timeout

---

src/test/java/org/tikv/common/TiSessionTest.java

The UT of `session.closeAwaitTermination` is not stable, because it depends on `time`.
remove the `time` from the UT.
Tests 
- Unit test
- No code
Code changes
Side effects

fix closeAwaitTermination UT

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/test/java/org/tikv/common/PDMockServerTest.java
src/test/java/org/tikv/common/TiSessionTest.java
src/test/java/org/tikv/common/importer/RawKVIngestTest.java
src/test/java/org/tikv/common/importer/RegionSplitTest.java
src/test/java/org/tikv/common/importer/SwitchTiKVModeTest.java
src/test/java/org/tikv/raw/CASTest.java
src/test/java/org/tikv/raw/MetricsTest.java
src/test/java/org/tikv/raw/RawKVClientTest.java
src/test/java/org/tikv/txn/ReplicaReadTest.java
src/test/java/org/tikv/txn/TXNTest.java

Currently RawKV and TxnKV cannot live together on the same TiKV cluster.
But all the test cases is running on the same TiKV cluster in ci.
So this PR try to provide a workaround to let ci pass.
Tests 
- Unit test
- No code
Code changes
Side effects

add parameter: isTest to TiConfiguration

---

src/main/java/org/tikv/cdc/CDCConfig.java
src/main/java/org/tikv/cdc/RegionCDCClient.java

This PR added row filter at RegionCDCClient's side to make sure the key range is effective.

Fix region key range while pulling CDC logs (#256)

---

src/main/java/org/tikv/common/importer/ImporterStoreClient.java

close https://github.com/tikv/client-java/issues/262
fix ImporterClient.ingest deadline exceeded 
use `conf.getIngestTimeout()` instead of `grpc timeout`
Tests 
- Unit test
- No code
Code changes
Side effects

fix ingest timeout

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java

close https://github.com/tikv/client-java/issues/260
Failed to init client for PD cluster with 240 clients
update pd get member timeout from 2s to 10s
Tests 
- Unit test
- No code
Code changes
Side effects

update pd get member timeout from 2s to 10s

---

src/test/java/org/tikv/common/importer/TxnKVIngestTest.java
src/test/java/org/tikv/txn/ReplicaReadTest.java

https://github.com/tikv/client-java/issues/270
This PR breaks compatibility tikv/tikv#10800.
disable TxnKV test as workaround
Tests 
- Unit test
- No code
Code changes
Side effects

workaround: disable TxnKV test

---

src/main/java/org/tikv/common/key/Key.java

We create a additional class 
https://github.com/tikv/migration/blob/main/online-bulk-load/src/main/scala/org/tikv/bulkload/SerializableKey.scala, because Key does not implmemnt Serializable.
let class Key implmemnts Serializable, so that SerializableKey is no more needed.
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to be …

let class Key implmemnts Serializable

---

src/main/java/org/tikv/common/importer/ImporterClient.java

https://github.com/tikv/migration/issues/30
bulk load: support deduplicate key
Tests 
- Unit test
- No code
Code changes
Side effects

bulk load: support deduplicate key

---

src/main/java/org/tikv/common/importer/ImporterClient.java
src/main/java/org/tikv/common/importer/ImporterStoreClient.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/util/BackOffer.java

https://github.com/tikv/migration/issues/23
leader may change during ingest
add ingest retry
Tests 
- Unit test
- No code
Code changes
Side effects

Ingest: add retry with not leader error

---

.gitignore
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/util/ChannelFactory.java

Signed-off-by: Xu Qiaolun <jamesxql@gmail.com>
keepalive with tikv server.

grpc: keepalive with tikv

---

src/main/java/org/tikv/cdc/CDCEvent.java
src/main/java/org/tikv/cdc/RegionCDCClient.java
src/main/java/org/tikv/common/MetricsServer.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/expression/RangeColumnPartitionPruner.java
src/main/java/org/tikv/common/parser/AstBuilder.java
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/StoreHealthyChecker.java
src/main/java/org/tikv/common/region/TiStore.java
src/main/java/org/tikv/common/streaming/StreamingResponse.java
src/main/java/org/tikv/raw/RawKVClient.java
src/main/java/org/tikv/txn/LockResolverClientV4.java
src/test/java/org/tikv/common/PDClientTest.java
src/test/java/org/tikv/common/RegionManagerTest.java
src/test/java/org/tikv/common/RegionStoreClientTest.java
src/test/java/org/tikv/common/codec/CodecTest.java
src/test/java/org/tikv/common/codec/MyDecimalTest.java
src/test/java/org/tikv/common/importer/SwitchTiKVModeTest.java
src/test/java/org/tikv/common/importer/TxnKVIngestTest.java
src/test/java/org/tikv/common/key/KeyTest.java
src/test/java/org/tikv/raw/MetricsTest.java
src/test/java/org/tikv/util/ReflectionWrapper.java

Simplified conditions, updated variable to final wherever applicable and removed unreachable throws Exception
Just refactoring and no functional impact
Tests
- Unit test

Simplified conditions, updated variable to final wherever applicable and removed unreachable throws Exception

---

README.md
pom.xml
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/util/ChannelFactory.java

https://github.com/tikv/client-java/issues/267
support tls
Tests 
- Unit test
- No code
Code changes
Side effects

support tls

---

pom.xml
src/main/java/org/tikv/common/PDChecker.java
src/main/java/org/tikv/common/PDClient.java
src/test/java/org/tikv/common/PDClientIntegrationTest.java
src/test/java/org/tikv/common/PDClientTest.java

Signed-off-by: Peng Guanwen <pg999w@outlook.com>
https://github.com/tikv/client-java/issues/268 needs to call pause checker in Java client. This PR adds the function.
Added functions:
- `PDClient.keepPauseChecker`
- `PDClient.stopKeepPauseChecker`
- `PDClient.resumeChecker`
Tests 
Code changes

PDClient: Add function to call pause checker API

---

src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java
src/test/java/org/tikv/common/importer/SwitchTiKVModeTest.java

Signed-off-by: Peng Guanwen <pg999w@outlook.com>
Fixes #282
The scheduler got removed after stopping.
Tests 

All keepTiKVToImportMode after stopped

---

src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/RegionCache.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/TiRegion.java
src/main/java/org/tikv/raw/RawKVClient.java

close https://github.com/tikv/client-java/issues/304 
When region splits, the region info on PD may not be updated in a few seconds.
Clients should use the new region info in `RegionEpochNotMatch ERROR` to update the local region cache.
OnRegionEpochNotMatch removes the old region and inserts new regions into the cache.
ref: https://github.com/tikv/client-go/blob/tidb-5.2/internal/locate/region_request.go#L985
Tests 
- Unit test
- No code
Code changes
Side effects
- …

fix Region Exception occurred EpochNotMatch

---

pom.xml
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Add metrics for callWithRetry & doBackOff

---

src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/util/BackOffer.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java

Tests 
- Unit test
- No code
Code changes
Side effects

fix backoff error when using grpc forward

---

src/main/java/org/tikv/common/PDClient.java

When starting many clients at the same time, PD may be the hotspot.
shuffle PD addresses so that clients call getMembers from different PD
Tests 
- Unit test
- No code
Code changes
Side effects

shuffle PD addresses so that clients call getMembers from different PD

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java

- Fix grpc forward bug.
- Modify default backoff from 100ms to 20ms.

Fix gRPC forward bug when store is unreachable

---

metrics/grafana/client_java_summary.json

Add more grafana panels, which are maps to the existing metrics.
Tests 
Code changes
Side effects

metrics: enrich grafana panel

---

src/main/java/org/tikv/common/PDClient.java

add log for init TiSession
Tests 
- Unit test
- No code
Code changes
Side effects

add log for init TiSession

---

src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/log/SlowLog.java
src/main/java/org/tikv/common/log/SlowLogEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogImpl.java
src/main/java/org/tikv/common/log/SlowLogSpan.java
src/main/java/org/tikv/common/log/SlowLogSpanEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogSpanImpl.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionErrorReceiver.java
src/main/java/org/tikv/common/util/BackOffer.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/raw/RawKVClientTest.java

add slow log
Tests 
- Unit test
- No code
Code changes
Side effects

add slow log

---

src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java

remove redundant seek leader logic that may cause retry.

Optimize seek leader store logic

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/exception/InvalidStoreException.java
src/main/java/org/tikv/common/operation/PDErrorHandler.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/common/RegionManagerTest.java

When the Java Client requests a store id that PD does not recognize, e.g., the PD was scaled-in and does not know about a scaled-out TiKV, the PD will respond with a `StatusRuntimeException` rather than an error wrapped by Response itself.
Thus we should resolve StatusRuntimeException so that the invalid store info can be dealt with correctly by clearing all-region/store cache info.

Fix pd request throws invalid store id

---

.github/labeler.yml
.github/pr-branch-labeler.yml
.github/workflows/labeler.yml
.github/workflows/pr-branch-labeler.yml
pom.xml

to identify which component the PR mainly contributes to
by adding the [labeler](https://github.com/marketplace/actions/labeler) github action
Tests 
- No code

add the labeler github action

---

src/main/java/org/tikv/common/TiSession.java

improve readability
1. refactor `getRegionStoreClientBuilder` to reduce code indent
2. try to use `getRegionStoreClientBuilder` to create `RawKVClient` and `KVClient`
Tests 

refactor getRegionStoreClientBuilder to improve readability

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiConfiguration.java
src/test/java/org/tikv/common/TiConfigurationTest.java

TiKV client currently assumes that TiFlash is deployed and starts a threadpool to periodically check tiflash replica status
https://github.com/tikv/client-java/issues/350
Added a boolean flag to determine if tiflash is enabled . The default value is false.
Tests 
- Unit test
Code changes
Side effects

Add a flag to determine if TiFlash is enabled

---

src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionErrorReceiver.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/util/BackOffFunction.java
src/main/java/org/tikv/common/util/BackOffer.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/test/java/org/tikv/raw/RawKVClientTest.java

close https://github.com/tikv/client-java/issues/353
we should check timeout during SeekLeader and SeekProxy

check timeout during SeekLeader and SeekProxy

---

src/main/java/org/tikv/common/log/SlowLog.java
src/main/java/org/tikv/common/log/SlowLogEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogImpl.java
src/main/java/org/tikv/raw/RawKVClient.java

close https://github.com/tikv/client-java/issues/362
Currently TiKV will only log `SlowLog` if `slowThresholdMS` exceeds.
Besides TiKV should also log `SlowLog `if error occures.

log SlowLog if error occures

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/region/StoreHealthyChecker.java

If `callWIthRetry` returns a null response, `getStore` will throw NullPointerException.

Fix NullPointerException in getStore

---

src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java

This pull request fixes the NPE triggered by the double retry of `seekLeaderStore`. These buggy lines would also introduce another issue like `peer id not match` because the meta of the region is not updated.
Once we change detected a reachable store we need to update the peer information of the region and retry in the most outside code.
Tests 
Code changes
Side effects
- Need to be included in the …

fix seekLeaderStore NPE

---

src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/raw/SmartRawKVClient.java

We find some initialization work that needs to do in the first gRPC call in `SmartRawKVClient` which might result in a timeout in the first few gRPC calls.
First run:
Second run:
To solve this problem, we may launch a `raw_get` request to warm up the runtime.

[close #375] warm up SmartRawKVClient while creating it

---

src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/util/ChannelFactory.java
src/test/java/org/tikv/common/TiConfigurationTest.java

Signed-off-by: Xiaoguang Sun <sunxiaoguang@pingcap.com>
Make gRPC idle timeout configurable
Make gRPC idle timeout configurable
Tests 
- Unit test
Code changes
closes: #380

[close #380] make gRPC idle timeout configurable

---

src/main/java/org/tikv/common/TiConfiguration.java
src/test/java/org/tikv/common/TiConfigurationTest.java

Fix warning in OLAP engine:
```
2021-12-08 05:18:47,334 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 05:19:01,130 WARN  org.tikv.common.region.AbstractRegionStoreClient             [] - forward request to store [tikv_host:tikv_port] for region[174126738]
2021-12-08 05:19:01,894 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 05:19:01,933 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] recovers to be reachable and canforward
2021-12-08 05:19:05,490 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 …
```

[close #370] make gRPC and TiKV health check configurable

---

src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/raw/SmartRawKVClient.java
src/test/java/org/tikv/raw/SmartRawKVClientTest.java

- fix #389 
make CircuitBreaker been created for every TiSession instead of every SmartRawKVClient
Tests 
- Unit test

[fix #389] move CircuitBreaker to TiSession

---

.github/workflows/gh-pages.yml

Issue Number: to #348
1. the generated rendered documents are not deployed in the gh-pages branch
2. the gh-pages action is configured in every pull request, but it can not deploy the rendered contents if the PR is not merged 
1. change the branch name from `main` to `master`, which was a mistake made in the former PR
2. remove the action trigger condition on `pull_request`, so that the action is only triggered when the PR is merged
- has been tested in my personal repository
- No code

[to #348] fix gh-pages can not deploy rendered documents

---

src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionErrorReceiver.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/test/java/org/tikv/BaseRawKVTest.java

close #433
Timeout in seekLeaderStore is not limited.
We should use `backoffer` for all the gRPC calls.

[close #433] fix calling getStoreById without backoffer

---

src/main/java/org/tikv/common/util/ConcreteBackOffer.java

In this PR https://github.com/tikv/client-java/pull/434, we remove the slowlog if backoffer is exceeded.
We should add it back.

[fix #433] fix slowlog in ConcreteBackOffer

---

src/main/java/org/tikv/common/TiConfiguration.java
src/test/java/org/tikv/common/TiConfigurationTest.java

Signed-off-by: Qishang Zhong <zhongqishang@gmail.com>
When I use the client in Flink , I get an error
```
Caused by: java.io.NotSerializableException: java.util.Optional
at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
... 48 more
```
Optional in the getter method
- Unit test
https://stackoverflow.com/questions/24547673/why-java-util-optional-is-not-serializable-how-to-serialize-the-object-with-suc

[close #446] Fix Optional fields type

---

src/main/java/org/tikv/common/TiConfiguration.java
src/test/java/org/tikv/common/TiConfigurationTest.java

cherry-pick #445 to release-3.1
Signed-off-by: Qishang Zhong <zhongqishang@gmail.com>
When I use the client in Flink , I get an error
```
Caused by: java.io.NotSerializableException: java.util.Optional
at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
... 48 more
```
Optional in the getter method
- Unit test
https://stackoverflow.com/questions/24547673/why-java-util-optional-is-not-serializable-how-to-serialize- …

[close #446] Fix Optional fields type (#445)

---

pom.xml
src/test/java/org/tikv/BaseRawKVTest.java
src/test/java/org/tikv/common/PDClientIntegrationTest.java
src/test/java/org/tikv/common/importer/RawKVIngestTest.java
src/test/java/org/tikv/common/importer/RegionSplitTest.java

Issue Number: close #462
Some tests in the master branch are not compatible with older versions of TiKV, we need to add some version constraints to these tests and furthermore, add integration compatibility tests for the master branch.
Use `Assume` to ignore some tests with version info reading from ENV.

[to #462] add version constraint for rawkv tests

---

src/main/java/org/tikv/txn/TwoPhaseCommitter.java
src/test/java/org/tikv/txn/TwoPhaseCommitterTest.java

Issue Number: close #465
Problem Description: implement AutoClosable for TwoPhaseCommitter

[close #465] implement AutoClosable for TwoPhaseCommitter

---

src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/test/java/org/tikv/util/ConcreteBackOfferTest.java

Issue Number: close #489
`ConcreteBackOffer` may trigger by multiple threads but the `backOffFunctionMap` is `HashMap` which is not thread-safe. This might trigger a race exception while this backoffer is shared between threads.

[close #489 ] fix backoffer data race

---

src/main/java/io/netty/buffer/PoolArena.java

Issue Number: to #480
Add allocation rate and duration metrics for `PoolArena`, including for thread-local cache allocation, `PoolChunkList` allocation and direct allocation.

[to #480] add netty mempool metrics

---

pom.xml
src/main/java/org/tikv/common/TiSession.java
src/test/java/org/tikv/raw/WarmupTest.java

close https://github.com/tikv/client-java/issues/497
Problem Description:  Request timeout when receiving NOT_LEADER error the first time.
The reason is that [error.toString](https://github.com/tikv/client-java/blob/v3.1.9/src/main/java/org/tikv/common/operation/RegionErrorHandler.java#L95) will trigger JVM ClassLoader load grpc error related classes, which costs more than 100ms.
Solution: let JVM JVM ClassLoader load grpc error related classes during warmup.

[close #497] let JVM ClassLoader load gRPC error related classes during warmup

---

scripts/proto.sh
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/TiConfiguration.java
src/main/java/org/tikv/common/log/SlowLog.java
src/main/java/org/tikv/common/log/SlowLogEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogImpl.java
src/main/java/org/tikv/common/log/SlowLogSpan.java
src/main/java/org/tikv/common/log/SlowLogSpanEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogSpanImpl.java
src/main/java/org/tikv/common/policy/RetryPolicy.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/common/log/SlowLogImplTest.java

Signed-off-by: Peng Guanwen <pg999w@outlook.com>
Issue Number: to #477 
Problem Description: **See [Proposal](https://pingcap.feishu.cn/docs/doccnyjWL25a7a0M8x8MGJ2wEWc#)**
- Interfaces in `SlowLog` and `SlowLogSpan` are adjusted.
- Time measuring in `SlowLogImpl` and `SlowLogSpanImpl` are refined.
- Log outputs are adjusted to align with tracing.
- Unit test **TBD**

[to #477] Change SlowLog interface to align with tracing

---

metrics/grafana/client_java_summary.json
src/main/java/io/grpc/stub/ClientCalls.java

Signed-off-by: haojinming <jinming.hao@pingcap.com>
Add metrics for ThreadlessExcutor LockSupport.park/unpark, them may take sone time when many threads are running. 
Issue Number: close #511 

[close #511] add LockSupport metrics

---

README.md

Issue Number: close #520
Problem Description: as the issues said, no direction for users and contributors to ask help
add slack and asktug links to the communication section.
- No code
- No code

[close #520] add communication method in README

---

pom.xml

Issue Number: close https://github.com/tikv/client-java/issues/542
An issue in protobuf-java allowed the interleaving of com.google.protobuf.UnknownFieldSet fields in such a way that would be processed out of order. A small malicious payload can occupy the parser for several minutes by creating large numbers of short-lived objects that cause frequent, repeated pauses. We recommend upgrading libraries beyond the vulnerable versions.
https://nvd.nist.gov/vuln/detail/CVE-2021-22569
Fix: upgrade protobuf-java from `3.12.0`  to `3.16.1`

[close #542] update protobuf version to 3.16.1

---

src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
src/test/java/org/tikv/raw/RawKVClientTest.java

Issue Number: close #540
This pull request adds an empty key check for `RawScanIterator.hasNext`, otherwise, if there is an empty key in TiKV, the scan will always return an empty set.

[close #540] rawkv: fix scan return empty set while exist empty key

---

src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
src/test/java/org/tikv/raw/RawKVClientTest.java

cherry-pick #541 to release-3.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
git pr https://github.com/tikv/client-java/pull/548
```
---
Issue Number: close #540
This pull request adds an empty key check for `RawScanIterator.hasNext`, otherwise, if there is an empty key in TiKV, the scan will always return an empty set.

[close #540] rawkv: fix scan return empty set while exist empty key (#541)

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/log/SlowLog.java
src/main/java/org/tikv/common/log/SlowLogEmptyImpl.java
src/main/java/org/tikv/common/log/SlowLogImpl.java
src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/common/log/SlowLogImplTest.java

Issue Number: to #556
Attach `cluster_id` and `pd_addresses` to slow log to distinguish the request destination while handling multiple TiKV clusters. 
Add `withFields` for `SlowLogImpl`, and use this interface to attach info dynamically while constructing the slow logger.
- Unit test

[to #556] slowlog: attach cluster_id and pd_addresses to slow log properties

---

src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionManager.java
src/test/java/org/tikv/common/PDClientMockTest.java
src/test/java/org/tikv/common/PDMockServerTest.java
src/test/java/org/tikv/common/SeekLeaderStoreTest.java

Issue Number: close #550
This pull request ignores exceptions while probing the leader/proxy store for a region's peer list including a unit test for mocking encountering some abnormal store while doing probing.
- Unit test

[close #550] rawkv: fix seek leader/proxy store early abort

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

[close #572] misc: fix syntax issues in github issue/pr templates

---

pom.xml

Issue Number: close #567
upgrade `jackson-databind` to 2.13.2.2 to fix CVE-2020-36518

[close #567] upgrade jackson-databind to 2.13.2.2 to fix CVE-2020-36518

---

dev/proto.sh

Issue Number: close #591
Update all the branches to the latest commit while precompiling.

[close #591] update all the branch of proto while precompiling to avoid commit miss

---

src/main/java/org/tikv/common/apiversion/RequestKeyV2Codec.java
src/main/java/org/tikv/common/apiversion/RequestKeyV2RawCodec.java
src/main/java/org/tikv/common/apiversion/RequestKeyV2TxnCodec.java
src/test/java/org/tikv/common/apiversion/RequestKeyCodecTest.java

Issue Number: close #issue_number
Problem Description: Current key prefix of API v2 is not extensible enough, because no more keyspace information could be attached to it which is against the original design for the https://github.com/tikv/rfcs/blob/master/text/0069-api-v2.md.
This pull request adds a reserved zero to represent the `default` keyspace.
- Unit test

[close #606]: change the default prefix for API v2

---

src/main/java/org/tikv/common/util/ChannelFactory.java
src/test/java/org/tikv/common/ChannelFactoryTest.java

Signed-off-by: Daemonxiao <735462752@qq.com>
TiSpark met some [problem](https://github.com/pingcap/tispark/issues/2376) when use TLS Reload.
Problem Description: tryReload() is used as a task in ScheduledFuture. When tryReload() throws an exception, the schedule will be suppressed which makes tryReload() will not work.
Add try-catch in tryReload().
```
// If any execution of the task encounters an exception, subsequent executions are suppressed.
private void tryReload() {
// Add exception handling to avoid schedule stop.
try {
if (needReload()) {
onChange.run();
}
} catch (Exception e) {
logger.error("Failed to reload cert!" + e);
}
}
```
- Unit test …

fix TLS reload doesn't work after delete cert file

---

docs/src/administration/configuration.md
docs/src/examples/rawkv.md

Issue Number: close #610, to #590

[close #610] [to #590] add docs for api v2 and tls reload

---

src/main/java/org/tikv/common/TiSession.java
src/main/java/org/tikv/common/Version.java
src/test/java/org/tikv/common/ApiVersionTest.java
src/test/java/org/tikv/common/MockThreeStoresTest.java
src/test/java/org/tikv/common/PDClientV2MockTest.java
src/test/java/org/tikv/common/PDMockServer.java

Issue Number: close #616
Check version bound in TiSession ctor.
- Unit test

[close #616] check store version while using API V2

---

src/main/java/org/tikv/common/operation/iterator/ConcreteScanIterator.java
src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
src/main/java/org/tikv/common/region/RegionStoreClient.java

Issue Number: close #623
Problem Description: If there is a region split between two queries, it may miss some regions.
I change the time of getting region from before scan to after scan.
When we build client, we will use region info in regionCache. After region split, it's outdated.
But when client try to scan the region, it will get the newest region info from pb. 
In the original code, we get region info before scan. So the region info is still outdated and it will use the old endKey to get next region. Using the old endKey may miss some regions that split during the two query.
I get the region info after scan to make sure the return value is newest.
- Unit test
- Manual test (add detailed scripts or …

[fix #623] region may be missed

---

src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/PDErrorHandler.java
src/test/java/org/tikv/common/PDMockServerTest.java
src/test/java/org/tikv/common/TimeoutTest.java

Issue Number: close #635
The `getMembers` is not limited by a `backoffer`, which might cause the exception will not throw in time. For example, a user might set the timeout of a request to 400ms, but if the PD is disconnected, the `getMembers` might sleep more than 400ms since the `backoffer` it used is not passed from the upper code.
Inject a `backoffer` for `getMembers` and check timeout before acquiring a channel from the pool.
- Unit test

[close #635] constraint the getMember timeout by inject a backoffer

---

src/main/java/org/tikv/raw/RawKVClient.java
src/test/java/org/tikv/raw/RawKVClientTest.java

Issue Number: close #634
The following code will hang in the master:
```java
HashMap<ByteString, ByteString> kvs = new HashMap<>();
for (int i = 0; i < MAX_RAW_BATCH_LIMIT * 4; i++) {
kvs.put(prefix.concat(ByteString.copyFromUtf8("key@" + i)), rawValue("value@" + i));
}
client.batchPut(kvs);
```
The code is dislocation while cherry picks other commits from release-3.1
- Unit test

[close #634] fix rawBatchPut hang while batch size is larger than MAX_RAW_BATCH_LIMIT

---

src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/PDErrorHandler.java
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/RegionStoreClient.java
src/test/java/org/tikv/common/PDClientV2MockTest.java
src/test/java/org/tikv/common/TimeoutTest.java

Issue Number: close #639
This pull request tries to reduce the lock granularity of `ReionStoreClient` and `PDClient`, we might block the requests while under a heavy workload.
1. Remove the synchronized keyword for RegionStoreBuilder.build, since the region cache's methods have already been synced.
2. Remove the synchronized keyword in PDClient's update leader logic, since the leader will be eventually updated to the latest one by the update leader scheduler.
- Unit test

[close #639] reduce lock granularity of RegionStoreClient and PDClient

---

docs/src/SUMMARY.md
docs/src/production-readiness.md

Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: close #657 
Problem Description: Add documents for production ready status of Java Client, to help users make decision about whether to use Java Client.
Add `production-readiness.md` and add link to index.
See [rendered](https://github.com/pingyu/client-java/blob/doc-production-readiness/docs/src/production-readiness.md).
- No code
- No code

[close #657] add production-readiness document

---

.github/workflows/license-checker.yml
src/main/java/org/tikv/common/ConfigUtils.java
src/main/java/org/tikv/common/region/RegionManager.java
src/test/java/org/tikv/common/GrpcUtils.java
src/test/java/org/tikv/common/RegionManagerTest.java

Problem Description: **client-java always selects the first TiFlash store which may cause read hotspot.**
Choose the TiFlash stores Round-Robin
- No code
- Unit test
- No code

[close #663] Select TiFlash Stores Round-Robin

---

src/test/java/org/tikv/common/MockRegionManager.java
src/test/java/org/tikv/util/RangeSplitterTest.java

Signed-off-by: shiyuhang <1136742008@qq.com>
Issue Number: close #693
Problem Description: **Add test for RangeSplitter**
Add test for RangeSplitter. reference: https://github.com/pingcap/tispark/blob/release-3.1/tikv-client/src/test/java/com/pingcap/tikv/util/RangeSplitterTest.java
- No code
- Unit test
- No code
- Need …

[close #693] Add test for RangeSplitter

---

pom.xml
src/main/java/io/grpc/internal/ClientCallImpl.java
src/main/java/io/netty/buffer/PoolArena.java
src/main/java/org/tikv/common/AbstractGRPCClient.java
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/main/java/org/tikv/common/util/BackOffFunction.java
src/main/java/org/tikv/common/util/ConcreteBackOffer.java
src/test/java/org/tikv/common/TsoBatchUsedUpTest.java

Issue Number: close #699
Problem Description: 
**Merge some critical hotfixes from release-3.3.1.11 for the RawKV feature.**

[close #699] Rebase release 3.3.1.11

---

pom.xml

Currently the client won't build on M1 Macs, because the protoc binary for aarch64 is missing.
Upgrade the protobuf dependency solves the problem.

fix by upgrade protobuf version so that it will build on M1 Macs

---

pom.xml
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/TiRegion.java

Issue Number: close #736
Judge store status before use. Use the next replica when the current replica is unreachable.
I have tested in TiSpark follower read with the first store killed, its success to request the next store.

[close #736] Select reachable store

---

pom.xml
src/main/java/org/tikv/common/region/RegionManager.java
src/main/java/org/tikv/common/region/StoreHealthyChecker.java
src/main/java/org/tikv/common/region/TiStore.java

Issue Number: close #749
https://github.com/pingcap/tispark/issues/2707
Problem Description: StoreHealthyChecker fails to check the status of TiFlash
Use isMppalive RPC to probe the status of TiFlash.
Manual test：
I have tested this locally with TiSpark. TiSpark will request TiFlash using client-java
1. TiSpark will with the client-java before  this PR will throw errors even if TiFlash is alive
```
23/05/20 15:31:12 WARN StoreHealthyChecker: fail to check TiFlash health, regrade as unhealthy
org.tikv.shade.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 1.999882667s. [closed=[], open=[[buffered_nanos=2005712916, waiting_for_connection]]]
at org.tikv.shade.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:287)
at …
```

[close #749] Fix health checking issue

---

src/test/java/org/tikv/common/apiversion/RequestKeyCodecTest.java

Issue Number: close #763 
Problem Description: **decode EpochNotMatch should ignore invalid region**
Complement v2 codec unit test cases for the scene that the region is out of keyspace.
Ref: #766 
- No.
- Unit test

[to #763] Complement v2 codec unit test cases

---

.github/config/tikv_rawkv.toml
.github/config/tikv_txnkv.toml
.github/config/tikv_v2.toml
.github/workflows/ci.yml
.github/workflows/ci_v2.yml

Issue Number: close #772 
Problem Description: **Integration tests in CI are flaky**
The reason of failure of integration tests in CI seems to be TiKV OOM.
We can see PD response with errors that "cluster is not bootstrapped" (see "Run Integration Test" in https://github.com/tikv/client-java/actions/runs/6390085322/job/17342615588?pr=770)
```
11949 [main] WARN  org.tikv.common.util.ConcreteBackOffer  - BackOffer.maxSleep 5000ms is exceeded, errors:
11949 [main] WARN  org.tikv.common.util.ConcreteBackOffer  - 
11.org.tikv.common.exception.GrpcException: 
ErrorType: PD_ERROR
Error: type: NOT_BOOTSTRAPPED
message: "cluster is not bootstrapped"
12.org.tikv.common.exception.GrpcException: 
ErrorType: PD_ERROR
Error: type: NOT_BOOTSTRAPPED
message: "cluster is not bootstrapped" …
```

[close #772] Fix flaky integration tests

---

src/main/java/org/tikv/common/apiversion/CodecUtils.java
src/main/java/org/tikv/common/apiversion/RequestKeyV2Codec.java
src/main/java/org/tikv/common/operation/RegionErrorHandler.java
src/test/java/org/tikv/common/apiversion/RequestKeyCodecTest.java

Issue Number: close #763 
Problem Description: **decode EpochNotMatch should ignore invalid region**
Cherry pick from [release-3.3.1.14](https://github.com/tikv/client-java/commits/release-3.3.1.14):
- #765 
- #766
- #768 
- No.
- Unit test

[to #763] Pick bug fixes of API v2 codec to master

---

pom.xml
src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
src/main/java/org/tikv/common/region/RegionStoreClient.java

This pull request bumps the gRPC version to 1.60.0 as the same deps of jetcd 0.7.7. Might related to https://github.com/grpc/grpc-java/issues/9340
I can reproduce the memory leak while using gRPC 1.48.0 as described in issue #782. When I bump the gRPC to 1.60.0 the error logs disappear even I run the test 100 times.
Issue Number: close #782 
Bump the gRPC version to 1.60.0.
- No code
- Unit test
- No code
- Breaking backward …

[close #782] bump grpc to 1.60.0

---

src/main/java/org/tikv/common/PDClient.java
src/main/java/org/tikv/common/TiDBJDBCClient.java
src/main/java/org/tikv/common/catalog/CatalogTransaction.java

Problem Description: ObjectMapper is actually a thread-safe object that can be reused to improve performance. Creating an ObjectMapper object is not fast.
Code Refactor.
- No code
- Unit test
- No code

[to #788] Reduce the number of ObjectMapper creations to improve performance
