tikv/client-java

- src/main/java/org/tikv/PDClient.java
- src/main/java/org/tikv/RawKVClient.java
- src/main/java/org/tikv/ReadOnlyPDClient.java
- src/main/java/org/tikv/TiConfiguration.java
- src/main/java/org/tikv/operation/iterator/RawScanIterator.java
- src/main/java/org/tikv/region/RegionManager.java
- src/main/java/org/tikv/region/TiRegion.java
- src/test/java/org/tikv/MockServerTest.java
add a KV mode to indicate whether to use Raw Regions.
> Add kv mode KV/RAW

- src/main/java/org/tikv/operation/PDErrorHandler.java
which may cause the error not be handled correctly.
> Fix when PD Response returns null

- pom.xml
- src/main/java/org/tikv/codec/Codec.java
So that it can be more flexible.
> Add other codec

- build.gradle
- src/main/java/org/tikv/common/util/ConcreteBackOffer.java
Signed-off-by: jackycchen <120505816@qq.com>
Fix two things:
1. The major thing, fix gradle build file bugs, and we can use "gradle clean build -x test" run successfully.
2. Secondly, optimize ConcreteBackOffer somethings according to go-client code.
> fix gradle build bugs, remove hadoop dependencies

- src/main/java/org/tikv/common/PDClient.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/util/ChannelFactory.java
- src/test/java/org/tikv/common/PDClientTest.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
Fix pd client cannot resolve ipv6 addresses
> Fix ipv6 address

- pom.xml
Signed-off-by: tison <wander4096@gmail.com>
This should fix #53 
cc @birdstorm
> Properly add include proto files

- README.md
> Correct README for new repo base url

- pom.xml
- scripts/proto.sh
use fixed version of proto  instead of master branch
> fix compile error because of proto

- README.md
close https://github.com/tikv/client-java/issues/69
> remove invalid link for TODO

- pom.xml
Shade grpc dependencies in pom to avoid conflict.
> Shade GRPC in pom to avoid conflict

- pom.xml
> Fix unshaded grpc dependency in pom

- README.md
- build.gradle
> Fix gradle build with shading

- README.md
- src/main/java/org/tikv/raw/RawKVClient.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
Use limit for all raw scan apis. Add max limit check.
> Update raw scan api

- src/main/java/org/tikv/common/util/BackOffFunction.java
- src/main/java/org/tikv/raw/RawKVClient.java
Close #80 
Add retry limit for rawPut API.
> Add retry limit for rawPut

- src/main/java/org/tikv/common/operation/KVErrorHandler.java
> fix qps is 0 for 10 minutes when node is down

- src/main/java/org/tikv/raw/RawKVClient.java
Fix #86 
RawGet changes the while (true) mechanism to a retry limit.
Tests 
- Manual test 
- Batch execution of RawGet verification.
> RawGet changes the while (true) mechanism to a retry limit.

- README.md
Remove bazel support from document.
> Remove bazel support from document

- pom.xml
> Update pom description

- src/main/java/org/tikv/common/PDClient.java
- src/main/java/org/tikv/common/ReadOnlyPDClient.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/region/RegionManager.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/region/TiRegion.java
- src/main/java/org/tikv/txn/AbstractLockResolverClient.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
> Support follower read

- src/main/java/org/tikv/common/region/RegionStoreClient.java
> Fix key not in region error

- src/main/java/org/tikv/common/columnar/TiChunkColumnVector.java
When zero month/day encounters in date, parsing will throw an exception.
Fixes by using DateFormat to parse beforehand.
> Fix zero in date parsing

- pom.xml
> Update pom version to v3.0.2

- src/main/java/org/tikv/common/codec/Codec.java
per #108 
The same logic shall be also ported to `Codec.decode` apis.
> Fix date time type decoding when contains zero

- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/raw/RawKVClient.java
Cherry-picked PRs from TiSpark-Java-Client to this repo for raw batch put.
Fixed some batch error.
> Fix raw batch put

- src/main/java/org/tikv/common/PDClient.java
In raw mode, the keys should not be encoded when calling `getRegionByKey()`.
> Fix getRegionByKey when using raw mode

- src/test/java/org/tikv/raw/RawKVClientTest.java
Add unit test for `rawScan` with empty result.
> Add raw scan test with empty result

- src/main/java/org/tikv/common/KVClient.java
- src/main/java/org/tikv/common/Snapshot.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/operation/iterator/ConcreteScanIterator.java
- src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
- src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/util/Batch.java
- src/main/java/org/tikv/common/util/ClientUtils.java
- src/main/java/org/tikv/common/util/ScanOption.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/main/java/org/tikv/txn/KVClient.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
Add following batch APIs to the client.
- BatchGet
- BatchScan
- BatchDelete
> Add Batch APIs

- src/main/java/org/tikv/raw/RawKVClient.java
> Add ScanPrefix API

- src/main/java/org/tikv/common/region/TiRegion.java
update function `getNextFollower`
- add random
- `public` -> `private`
- return `Peer` -> `void`
> add random to function getNextFollower

- src/main/java/org/tikv/common/KVClient.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/util/ClientUtils.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/main/java/org/tikv/txn/KVClient.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
> Add DeleteRange API

- src/main/java/org/tikv/common/operation/KVErrorHandler.java
If the error message is `Raft Proposal Dropped`, it means that the store is in the middle of a transition. It should be able resolved by a retry.
> Retry when error is raft proposal dropped

- src/main/java/org/tikv/common/util/BackOffer.java
- src/main/java/org/tikv/raw/RawKVClient.java
Corresponds with the same configurations in Client-Go.
> Modify default RawKV backoff time

- scripts/proto.sh
- src/main/java/org/tikv/common/region/TiRegion.java
Update kvproto version for TTL support.
> Update kvproto version

- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/test/java/org/tikv/common/GrpcUtils.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
> Add TTL support

- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/region/RegionManager.java
> Fix cache missing because of recreation of RegionManager

- pom.xml
> Modify shade pattern from shade.x to org.tikv.shade.x

- src/main/java/org/tikv/common/util/ClientUtils.java
- src/main/java/org/tikv/raw/RawKVClient.java
batch put may cause StackOverflow because of retry strategy.
> Fix batch put StackOverflow

- src/main/java/org/tikv/common/region/RegionManager.java
small lock optimization does not have a significant effect, thus we revert it for now.
> Revert small lock optimization

- pom.xml
- src/main/java/org/tikv/common/AbstractGRPCClient.java
- src/main/java/org/tikv/common/ConfigUtils.java
- src/main/java/org/tikv/common/KVClient.java
- src/main/java/org/tikv/common/PDClient.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/Utils.java
- src/main/java/org/tikv/common/operation/KVErrorHandler.java
- src/main/java/org/tikv/common/operation/iterator/ConcreteScanIterator.java
- src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
- src/main/java/org/tikv/common/policy/RetryMaxMs.java
- src/main/java/org/tikv/common/policy/RetryPolicy.java
- src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
- src/main/java/org/tikv/common/region/RegionManager.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/util/ClientUtils.java
- src/main/java/org/tikv/common/util/DeleteRange.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/main/java/org/tikv/txn/KVClient.java
- src/test/java/org/tikv/common/RegionManagerTest.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
This is a combined PR for reviewers.
- Add Prometheus for java client.
- Fix incorrect retry policy when the region splits.
- Update Configuration settings.
- Add TTL API support for raw client.
> Optimize and Fix minor bugs on master

- scripts/proto.sh
- src/main/java/org/tikv/common/ConfigUtils.java
- src/main/java/org/tikv/common/KVClient.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/policy/RetryPolicy.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/util/ClientUtils.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/main/java/org/tikv/txn/KVClient.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
Add atomic API support for raw client
Including:
- putIfAbsent
- batchPut
- batchDelete
> Add atomic api support

- src/main/java/org/tikv/common/operation/KVErrorHandler.java
- src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
> Fix update leader logic error

- scripts/proto.sh
- src/main/java/org/tikv/common/region/RegionStoreClient.java
Refactor for https://github.com/pingcap/kvproto/pull/742
> Refactor method and variable name

- README.md
> Add docs for configurations

- src/test/java/org/tikv/raw/RawKVClientTest.java
Add some batch put testing strategy
Can be configured with JVM parameters:
- `tikv.test.batch_put_strategy`
- the testing strategy
- string, options `random`, `hotspot`
- default `random`
- `tikv.test.batch_put_cnt`
- size of batch put data set
- long
- default `1000`
> Add test batch put strategy

- pom.xml
> Update version to v3.1.0-SNAPSHAOT

- pom.xml
> Update version to 3.1.0-SNAPSHAOT (#152)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> Add Issue and PR template

- README.md
adjust markdown code, for properly render README.
As code, straightforward.
> adjust markdown code

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
cherry-pick #157 to release-3.1
Tests 
- No code
> add issue and pr template (#157)

- src/main/java/org/tikv/common/util/ClientUtils.java
There was an un-necessary list copy in groupKeysByRegion api.
remove it.
Tests 
- Unit test
> Remove unnecessary list copy

- src/main/java/org/tikv/common/region/RegionManager.java
cherry-pick #170 to master branch
> invalidate all region cache on store when store id not found (#170)

- src/main/java/org/tikv/common/policy/RetryPolicy.java
Add a new metrics that records the number of gRPC request retries for each type.
> Add request retry number metrics for client

- .github/ISSUE_TEMPLATE/bug_report.md
some commented statement is inappropriate in the bug report template.
> Remove incorrect content in bug report template

- scripts/proto.sh
- shell.nix
Fix missing environment variables in `nix-shell --pure`.
Tests 
```bash
nix-shell --pure shell.nix
mvn clean install -Dmaven.test.skip=true
```
> fix build issue in `nix-shell --pure`

- pom.xml
we should update pom version of master branch to 3.2.0-SNAPSHOT, because we already have a `release-3.1` branch.
Tests 
- Unit test
- No code
Code changes
Side effects
> update pom version to 3.2.0-SNAPSHOT

- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/region/RegionManager.java
close https://github.com/tikv/client-java/issues/205
Tests 
- Unit test
- No code
Code changes
Side effects
> fix not stop scheduler

- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/raw/RawKVClient.java
support putAtomic and deleteAtomic API in RawKVClient
Tests 
- Unit test
- No code
Code changes
Side effects
> support putAtomic and deleteAtomic API

- src/main/java/org/tikv/common/ConfigUtils.java
- src/main/java/org/tikv/common/TiConfiguration.java
- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
- src/main/java/org/tikv/common/region/RegionManager.java
- src/main/java/org/tikv/common/region/StoreHealthyChecker.java
- src/test/java/org/tikv/common/RegionManagerTest.java
Cherry-pick https://github.com/tikv/client-java/pull/235
Tests 
- Unit test
- No code
Code changes
Side effects
> Optimize grpc-forward strategy

- src/main/java/org/tikv/common/TiSession.java
- src/test/java/org/tikv/common/TiSessionTest.java
cherry-pick https://github.com/tikv/client-java/pull/238
Tests 
- Unit test
- No code
Code changes
Side effects
> TiSession support graceful close (#238)

- pom.xml
shade jackson
Tests 
- Unit test
- No code
Code changes
Side effects
> shade jackson

- README.md
formatting of PD and TiKV hyperlink
Tests 
- No code
> Fixed formatting of PD and TiKV hyperlink

- src/main/java/org/tikv/common/importer/ImporterClient.java
Ingest: fix split batch bug 
Tests 
- Unit test
- No code
Code changes
Side effects
> Ingest: fix split batch bug 

- pom.xml
update version to 3.1.5-SNAPSHOT
Tests 
- Unit test
- No code
Code changes
Side effects
> update version to 3.1.5-SNAPSHOT

- src/main/java/org/tikv/common/operation/RegionErrorHandler.java
remove log for EpochNotMatch
Tests 
- Unit test
- No code
Code changes
Side effects
> remove log for EpochNotMatch

- src/main/java/org/tikv/common/PDClient.java
update initCluster log level to error
Tests 
- Unit test
- No code
Code changes
Side effects
> update initCluster log level to error

- pom.xml
Update version to 3.1.6-SNAPSHOT
> Update version to 3.1.6-SNAPSHOT

- pom.xml
update pom version to 3.1.7-SNAPSHOT
Tests 
- Unit test
- No code
Code changes
Side effects
> update pom version to 3.1.7-SNAPSHOT

- pom.xml
> Update jackson databind version to 2.10.5.1

- pom.xml
Tests 
- Unit test
- No code
Code changes
Side effects
> update pom version to 3.1.8-SNAPSHOT

- src/main/java/org/tikv/common/region/RegionStoreClient.java
> Fix typo in error message

- src/main/java/org/tikv/common/PDClient.java
update error log
Tests 
- Unit test
- No code
Code changes
Side effects
> update error log

- pom.xml
Tests 
- Unit test
- No code
Code changes
Side effects
> update pom version to 3.1.9-SNAPSHOT

- pom.xml
Tests 
- Unit test
- No code
Code changes
Side effects
> update pom version to 3.1.10-SNAPSHOT

- Makefile
simplify build/test/format tasks
add a Makeflie to wrap commonly used commands
Tests 
- No code
> add Makeflie to simplify build/test/format tasks

- src/main/java/org/tikv/common/operation/RegionErrorHandler.java
- src/main/java/org/tikv/common/policy/RetryPolicy.java
- src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
- src/main/java/org/tikv/common/region/RegionErrorReceiver.java
- src/main/java/org/tikv/common/region/RegionManager.java
- src/main/java/org/tikv/common/util/BackOffFunction.java
- src/main/java/org/tikv/common/util/BackOffer.java
- src/main/java/org/tikv/common/util/ConcreteBackOffer.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
cherry pick https://github.com/tikv/client-java/pull/352
> check timeout during SeekLeader and SeekProxy (#352)

- .github/labeler.yml
- .github/pr-branch-labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/pr-branch-labeler.yml
cherry-pick #347 to release 3.1
Tests 
- No code
> add the labeler github action (#347)

- Makefile
cherry-pick #346 to release 3.1
Tests 
- No code
> add Makeflie to simplify build/test/format tasks (#346)

- pom.xml
update pom version to 3.1.11-SNAPSHOT
> update pom version to 3.1.11-SNAPSHOT

- src/main/java/org/tikv/common/TiSession.java
- src/main/java/org/tikv/raw/SmartRawKVClient.java
> fix SmartRawKVClient close

- pom.xml
update pom version to 3.1.12-SNAPSHOT
> update pom version to 3.1.12-SNAPSHOT

- metrics/grafana/client_java_summary.json
close https://github.com/tikv/client-java/issues/399
add grafana metrics for circuit break
> [close #399] add grafana metrics for circuit break

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
close #405
for PR template, add a PR format section
for issue template, add the labels by default
Tests 
- No code
> [close #405] update PR and issue template

- .ci/integration_test.groovy
> test with tikv master branch

- docs/src/SUMMARY.md
- docs/src/introduction/introduction.md
Issue Number: to #348
Problem Description: the original document starts with "quick start", it's better to have an introduction page to describe the target reader and what this document can help to these users.
Added an introduction page
- No code
- No code
> [to #348] add introduction for the whole document

- .ci/integration_test.groovy
- .ci/test.sh
- config/tidb.toml
- config/tikv_rawkv.toml
- config/tikv_txnkv.toml
- src/main/java/org/tikv/common/TiConfiguration.java
- src/test/java/org/tikv/BaseRawKVTest.java
- src/test/java/org/tikv/BaseTxnKVTest.java
- src/test/java/org/tikv/common/TiConfigurationTest.java
- src/test/java/org/tikv/common/TiSessionTest.java
- src/test/java/org/tikv/raw/MetricsTest.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
- src/test/java/org/tikv/raw/SmartRawKVClientTest.java
- src/test/java/org/tikv/txn/ReplicaReadTest.java
- src/test/java/org/tikv/txn/TXNTest.java
- src/test/java/org/tikv/util/TestUtils.java
Issue Number: close https://github.com/tikv/client-java/issues/425
Problem Description: **The UT is not stable, cause RawKV and TxnKV cannot live on one TiKV instance now.**
Start two TiKV instance for UT, one for RawKV test and another for TxnKV test.
- No code
- Unit test
- No code
- Need to cherry-pick to …
> [close #425] make test stable

- .github/workflows/gh-pages.yml
- .gitignore
- README.md
- src/main/java/org/tikv/common/expression/visitor/PartAndFilterExprRewriter.java
- src/main/java/org/tikv/common/importer/ImporterStoreClient.java
- src/main/java/org/tikv/common/types/DataType.java
- src/main/java/org/tikv/common/util/RangeSplitter.java
- src/main/java/org/tikv/txn/TwoPhaseCommitter.java
- src/main/java/org/tikv/txn/TxnStatus.java
Signed-off-by: Peng Guanwen <pg999w@outlook.com>
Issue Number: part of #348 
Problem Description: Add CI support for javadoc and fix incorrect docs.
The API doc will be hosted on https://tikv.github.io/client-java/apidocs
- No code
- No code
> [to #348] Add javadoc

- pom.xml
https://github.com/tikv/client-java/issues/427
Support auto release to maven repo.
> [to #427] set autoReleaseAfterClose to true

- Makefile
> [close #467] clean pb repo and target while make clean

- src/main/java/org/tikv/common/log/SlowLogImpl.java
- src/main/java/org/tikv/common/log/SlowLogSpanImpl.java
close https://github.com/tikv/client-java/issues/435
SimpleDateFormat is not threadsafe.
Use different SimpleDateFormat object for different threads.
> [close #435] SimpleDateFormat is not threadsafe

- .github/license-checker.yml
- pom.xml
- src/main/java/io/grpc/internal/ClientCallImpl.java
- src/main/java/io/grpc/netty/NettyChannelBuilder.java
- src/main/java/io/grpc/netty/NettyClientHandler.java
- src/main/java/io/grpc/netty/NettyClientStream.java
- src/main/java/io/grpc/netty/WriteQueue.java
- src/main/java/io/grpc/stub/ClientCalls.java
- src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java
- src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java
- src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java
- src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java
- src/main/java/io/netty/handler/codec/http2/Http2OutboundFrameLogger.java
Issue Number: to 480
add grpc and netty source code, so that we can add metrics inside grpc and netty in next pr.
> [to #480] add grpc and netty source code

- src/main/java/io/grpc/internal/ClientCallImpl.java
- src/main/java/io/grpc/netty/NettyClientHandler.java
- src/main/java/io/grpc/netty/NettyClientStream.java
- src/main/java/io/grpc/netty/WriteQueue.java
- src/main/java/io/grpc/stub/ClientCalls.java
- src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java
- src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java
- src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java
- src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java
- src/main/java/io/netty/handler/codec/http2/Http2OutboundFrameLogger.java
- src/main/java/org/tikv/common/PDClient.java
- src/main/java/org/tikv/common/policy/RetryPolicy.java
- src/main/java/org/tikv/common/region/AbstractRegionStoreClient.java
- src/main/java/org/tikv/common/region/RegionManager.java
- src/main/java/org/tikv/common/region/RegionStoreClient.java
- src/main/java/org/tikv/common/util/ConcreteBackOffer.java
- src/main/java/org/tikv/common/util/HistogramUtils.java
- src/main/java/org/tikv/raw/RawKVClient.java
- src/main/java/org/tikv/raw/SmartRawKVClient.java
Issue Number: close #480
add metrics inside grpc and netty
> [close #480] add metrics inside grpc and netty

- metrics/grafana/client_java_summary.json
Issue Number:  to #480
update grafana for netty grpc metrics
> [to #480] update grafana for netty grpc metrics

- pom.xml
close https://github.com/tikv/client-java/issues/509
update google-gson to 2.8.9
> [close #509] update google-gson to 2.8.9

- src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java
- src/main/java/org/tikv/common/operation/iterator/ScanIterator.java
- src/test/java/org/tikv/raw/RawKVClientTest.java
> Revert "[close #540] rawkv: fix scan return empty set while exist empty key (#541)"

- scripts/proto.sh
> Revert "[close #591] update all the branch of proto while precompiling to avoid commit miss (#592)"

- README.md
- docs/src/examples/quick-start.md
- docs/src/examples/rawkv.md
- docs/src/examples/txnkv.md
Signed-off-by: pingyu <yuping@pingcap.com>
Issue Number: close #666 
Problem Description: **Some issues in examples**
- Fix issues in examples.
- To README: add TxnKV example, change demo link to https://tikv.github.io/client-java/, and other tiny polish.
- No code
> [close #666] Fix some issues in example and README

- pom.xml
Issue Number: close #issue_number
Problem Description: **TBD**
- No code
- Unit test
- No code
> [close #730] update version to 3.3.3

- pom.xml
> fix version to 3.3.4

- pom.xml
Issue Number: close #755
Problem Description: **TBD**
- No code
- Unit test
- No code
> [close #755] uprade version to 3.3.5

- src/main/java/org/tikv/common/operation/RegionErrorHandler.java
Issue Number: close #issue_number
Problem Description: **TBD**
- No code
- Unit test
- No code
> [cherry-pick] ignore invalid region while decoding EpochNotMatch

- src/main/java/org/tikv/common/apiversion/CodecUtils.java
- src/main/java/org/tikv/common/apiversion/RequestKeyV2Codec.java
- src/test/java/org/tikv/common/apiversion/RequestKeyCodecTest.java
Issue Number: close #issue_number
Problem Description: **TBD**
- No code
- Unit test
- No code
> fix region out of keyspace
